### PR TITLE
Add letter_opener gem

### PR DESCRIPTION
**Pull request by antwonlee**
Because:

Somebody in the team wanted password forget and registration
transactional emails.

This commit:

Just added letter_opener gem and configured the development env file.

### CODE REVIEW

**Comment by patrick-rebel** [comment]
For what purpose do we need  password forget and registration transactional emails?

**Comment by antwonlee** [comment]
from @thedanotto 

>>>  I personally would rather have fun and build something I'm proud of, rather than make my goal winning. By the way, when do we need to submit the final project? Also, I used devise because I know it. I'm pretty sure that using devise or monban will not factor in. Also, Instagram does have a password reset page. https://www.instagram.com/accounts/password/reset/

**Comment by antwonlee** [comment]
@patrick-rebel I guess we don't need it since it is not a requirement.

**Comment by thedanotto** [comment]
Ok, maybe it's not an explicit requirement of the project. But do we want to leave our users without an ability to login to our website if they forget their password?

**Comment by patrick-rebel** [comment]
I saw in the video that @antwonlee sent us about code review that the people at upcase are very happy when the numbers say +15 and -100 lines of code. In this case we have no users but we have people who judge our code. I think if it is not a requirement than we can leave it out.

**Pull request closed without merging**
