### PR TITLE
Adds a diagram to show the db schema.

### PR DESCRIPTION
**Pull request by Jesus**
Obviously we don't have to stick to this but it'll help us to have a global view of the database schema.

### CODE REVIEW

**Comment by Jesus** [comment]
The tests are failing just because we need to update some gems. That'll get sorted out when #7 is pulled into master.

**Comment by patrick-rebel** [comment]
This test is still failing. I had the same problem but when I run bundle update the problem was solved.

**Comment by patrick-rebel** [comment]
I noticed that the Gemfile.lock is the same as mine in my branch monbanvsdevise, is there a reason behind this why we are making a seperate branch, merge into master and rebase in my branch?

**Comment by Jesus** [comment]
The Gemfile.lock in this branch is the same as in master.

Your branch can be rebased to pull the Gemfile.lock from master.

**Pull request merged**
